const INFURA_URL = "https://rinkeby.infura.io/v3/";

const UNISWAP_FACTORT_CONTRACT_RINKEBY_ADDRESSS =
  "0xf5D915570BC477f9B8D6C0E980aA81757A3AaC36";

exports.INFURA_URL = INFURA_URL;
exports.UNISWAP_FACTORT_CONTRACT_RINKEBY_ADDRESSS = UNISWAP_FACTORT_CONTRACT_RINKEBY_ADDRESSS;
